#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/ui
#
# IDENTIFICATION
#    src/backend/ui/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/ui
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = optimizer_ui.o

include $(top_srcdir)/src/backend/common.mk
